services:
  whoami:
    image: traefik/whoami
    container_name: simple-service
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`test.med5.com.br`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.routers.whoami.tls.certresolver=letencrypt"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
        - proxy
networks:
  proxy:
    name: proxy