version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
      - ./letsencrypt:/letsencrypt
    networks:
      - med5-network

  # Backend API
  api:
    build: ./backend
    container_name: med5-api
    restart: unless-stopped
    environment:
      - DB_HOST=seu-rds-endpoint.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=med5
      - DB_USER=med5_user
      - DB_PASSWORD=senha_segura
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`h-backend.med5.com.br`) || PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.middlewares=secure-headers,api-strip-prefix,rate-limit"
      - "traefik.http.services.api.loadbalancer.server.port=3000" # Ajuste conforme sua API
    networks:
      - med5-network
    depends_on:
      - redis
      - traefik

  # Frontends (exemplo para app, repita para outros)
  app:
    image: med5/app:latest
    container_name: med5-app
    restart: unless-stopped
    environment:
      - API_URL=https://api.med5.exemplo.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`h-app.med5.com.br`)"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app.middlewares=secure-headers"
      - "traefik.http.services.app.loadbalancer.server.port=80"
    networks:
      - med5-network
    depends_on:
      - api
      - traefik

  # Redis
  redis:
    image: redis:alpine
    container_name: med5-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - med5-network

networks:
  med5-network:
    driver: bridge

volumes:
  redis_data:
    driver: local