http:
  middlewares:
    traefik-auth:
      basicAuth:
        users:
          - "usuario:$$2y$$05$$MBC2h4.kdM9D6WZTEVQj0.XeGxE/7Dz7qN3JtY6x1UZKUu5Jb9QaO"  # Substitua pelo hash real

    secure-headers:
      headers:
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true

    api-strip-prefix:
      stripPrefix:
        prefixes:
          - "/api"

    rate-limit:
      rateLimit:
        average: 100
        burst: 50

  routers:
    traefik-dashboard:
      rule: "Host(`monitor.med5.com.br`)"
      entryPoints: ["websecure"]
      service: "api@internal"
      middlewares: ["traefik-auth"]
      tls:
        certResolver: "letsencrypt"