global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false
  debug: true  # Ativar para diagnóstico

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: "med5-network"  # Especificar a rede explicitamente
    watch: true
    swarmMode: false
    useBindPortIP: false
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "salesfilho@med5.com.br"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"