# Configuração global
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Configuração da API e Dashboard
api:
  dashboard: true
  insecure: true # true Desabilitar acesso inseguro ao dashboard
  debug: true # true Habilitar logs de depuração

# Pontos de entrada
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: "med5.com.br"
            sans:
              - "*.med5.com.br"

# Provedores
providers:
  docker:
    exposedByDefault: false
    network: med5-network
    watch: true
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

# Resolvedores de certificados
certificatesResolvers:
  myresolver:
    acme:
      email: "salesfilho@med5.com.br"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"