version: '3.8'

services:
  
  app:
    image: 761160219175.dkr.ecr.us-east-1.amazonaws.com/med5/app:test
    container_name: med5-app
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`h-app.med5.com.br`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app.middlewares=secure-headers"
      - "traefik.http.services.app.loadbalancer.server.port=80"

    networks:
      - proxy

  redis:
    image: redis:alpine
    container_name: med5-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - proxy

networks:
  proxy:
    name: proxy

volumes:
  redis_data:
    driver: local