
services:
  # Serviço do aplicativo med5
  med5-app:
    image: 761160219175.dkr.ecr.us-east-1.amazonaws.com/med5/app:test
    container_name: med5-app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_net

  med5-api:
    image: 761160219175.dkr.ecr.us-east-1.amazonaws.com/med5/backend:test
    container_name: med5-api
    command: ./run.sh
    restart: always
    tty: true
    working_dir: /srv/app
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - static-content:/srv/app/static
      - media-content:/srv/app/media
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_net
      - app-network
  med5-meet:
    image: 761160219175.dkr.ecr.us-east-1.amazonaws.com/med5/node:latest
    container_name: med5-meet
    command: node server.js
    restart: always
    tty: true
    working_dir: /srv/app
    depends_on:
      - redis
    volumes:
      - static-content:/srv/app/static
      - media-content:/srv/app/media
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_net
      - app-network
  med5-ws:
    image: 761160219175.dkr.ecr.us-east-1.amazonaws.com/med5/backend:test
    container_name: med5-ws
    command: ./run_ws.sh
    restart: always
    tty: true
    working_dir: /srv/app
    depends_on:
      - redis
    volumes:
      - static-content:/srv/app/static
      - media-content:/srv/app/media
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_net
      - app-network

  med5-transcript:
    image: 761160219175.dkr.ecr.us-east-1.amazonaws.com/med5/transcript:latest
    container_name: med5-transcript
    command: ./run.sh
    restart: always
    tty: true
    working_dir: /srv/app
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_net


  redis:
    image: redis:latest
    container_name: redis
    restart: always
    tty: true
    networks:
      - app-network


networks:
  traefik_net:
    name: traefik_net
    driver: bridge
    external: true  # Conectado na rede do Traefik existente

  app-network:
    name: app-network
    driver: bridge
    internal: true  # Isola serviços sensíveis


#Volumes
volumes:
  static-content:
  media-content:
